tasks:
  - name: Download, Unzip & Install AWS CLI
    init: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    command: 
      unzip awscliv2.zip &&
      sudo ./aws/install &&
      rm awscliv2.zip
  - name: Install NPM Global Modules
    command: 
      npm install -g serverless


# .gitpod.yml reference:
# https://www.gitpod.io/docs/config-start-tasks