service: finapp-backend-aws-node-poc-v1
frameworkVersion: '2 || 3'

# Plugins for Serverless project
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev # Default stage to be used. Default is "dev"
  region: ap-south-1
  stackName: finapp-backend-aws-node-poc-v1-stack # Use a custom name for the CloudFormation stack
  apiName: finapp-backend-aws-node-poc-v1-api # Use a custom name for the API Gateway API

functions:
  hello:
    handler: handler.hello
    events: # The Events that trigger this Function
      - httpApi: # HTTP API endpoint (API Gateway v2)
          path: /
          method: get
  dummy:
    handler: handler.dummy
    events: # The Events that trigger this Function
      - http: # REST API endpoint (API Gateway v1)
          path: / # Path for this endpoint
          method: get
